---
- include_tasks:                '../tasks/install_packages.yml'
- include_tasks:                '../tasks/add_users_to_groups.yml'
- include_tasks:                '../tasks/install_files.yml'
- include_tasks:                '../tasks/adjust_files.yml'
- include_tasks:                '../tasks/enable_services.yml'
- include_tasks:                '../tasks/restart_services.yml'
  when:                         install_files_result.changed
                                or adjust_files_result.changed
- include_tasks:                '../tasks/start_services.yml'
