---
- include:                      '../tasks/install_packages.yml'
- include:                      '../tasks/install_files.yml'
- include:                      '../tasks/template_files.yml'
- include:                      '../tasks/enable_services.yml'
- include:                      '../tasks/restart_services.yml'
  when:                         install_files_result.changed
                                or template_files_result.changed
