---
- include:                      '../tasks/install_packages.yml'
- include:                      '../tasks/add_users_to_groups.yml'
- include:                      '../tasks/install_files.yml'
- include:                      '../tasks/enable_services.yml'
- include:                      '../tasks/restart_services.yml'
  when:                         install_files_result.changed
- include:                      '../tasks/start_services.yml'
